import Link from 'next/link';
import { notFound, redirect } from 'next/navigation';
import { AppHeader } from '@/components/header';
import { requireUser } from '@/lib/auth';
import { LockIcon, InfoIcon } from '@/components/icons';
import { CheckoutButton } from '@/components/checkout-button';
import { getPriceAmount } from '@/lib/stripe';
import { formatMoney } from '@/lib/format';

export const dynamic = 'force-dynamic';

export default async function PaymentPage({ params }: { params: { id: string } }) {
  const { user, supabase } = await requireUser();

  const { data: test } = await supabase
    .from('photo_tests')
    .select('id, status, min_age, max_age, photos(count)')
    .eq('id', params.id)
    .maybeSingle();

  if (!test) notFound();
  if (test.status !== 'pending_payment') {
    // Already paid — send them to the right place
    if (test.status === 'completed') redirect(`/report/${test.id}`);
    redirect(`/submitted/${test.id}`);
  }

  const count = (test.photos as any)?.[0]?.count ?? 0;
  const { amount, currency } = await getPriceAmount();
  const total = formatMoney(amount, currency);

  return (
    <>
      <AppHeader email={user.email} />
      <main className="mx-auto max-w-[480px] px-6 pb-24 pt-12 animate-fadeUp">
        <Link
          href="/upload"
          className="mb-4 inline-block bg-transparent text-[14px] font-medium text-ink-muted no-underline hover:text-ink"
        >
          ← Back to photos
        </Link>
        <h1 className="m-0 mb-6 font-display text-[32px] font-medium">Review &amp; pay</h1>

        <div className="mb-4 rounded-lg border border-border bg-surface p-6 shadow-sm">
          <Row label={`Photo test · ${count} photos`} value={total} mono />
          <Row label={`Audience · Women ${test.min_age}-${test.max_age}`} value="100 voters" mono />
          <div className="my-2 h-px bg-border" />
          <div className="flex justify-between py-1.5 text-[18px] font-semibold">
            <span>Total</span>
            <span className="font-mono">{total}</span>
          </div>
        </div>

        <div className="mb-5 flex items-start gap-2.5 rounded-xl bg-primary-soft px-4 py-3.5">
          <InfoIcon className="mt-px flex-shrink-0 text-primary" />
          <p className="m-0 text-[13px] text-ink-muted">
            Reactions are generated by AI-simulated women, not real people. This is a private rehearsal of your photos.
          </p>
        </div>

        <CheckoutButton testId={test.id} total={total} />
        <p className="m-0 mt-3.5 text-center text-[12px] text-ink-subtle">
          Payments handled by Stripe · cards never touch our servers
        </p>
        <p className="m-0 mt-3 flex items-center justify-center gap-1.5 text-[12px] text-ink-subtle">
          <LockIcon /> Encrypted end-to-end
        </p>
      </main>
    </>
  );
}

function Row({ label, value, mono }: { label: string; value: string; mono?: boolean }) {
  return (
    <div className="flex justify-between py-2.5 text-[15px]">
      <span className="text-ink-muted">{label}</span>
      <span className={mono ? 'font-mono' : ''}>{value}</span>
    </div>
  );
}
